"""initial migration

Revision ID: 547d8b534025
Revises: 87703efaefe9
Create Date: 2024-08-19 01:26:54.908982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547d8b534025'
down_revision: Union[str, None] = '87703efaefe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contact_us', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_us', type_='foreignkey')
    op.drop_column('contact_us', 'user_id')
    # ### end Alembic commands ###
